const words = [
    ["astronomer", "天文学家"],
    ["banquet", "宴会"],
    ["oblivious", "健忘的, 无意识的"],
    ["crutch", "轮椅/拐杖"],
    ["stagnant", "停滞的"],
    ["tedious", "乏味的"],
    ["demoralizing", "令人沮丧的"],
    ["steamroll", "平推"],
    ["aperture", "光圈"],
    ["vicinity", "附近, 周围"],
    ["tweening", "补间/插值"],
    ["chasm", "裂谷, 深渊"],
    ["sentient", "有感觉的, 有意识的"],
    ["damp", "潮湿的"],
    ["incentivize", "激励"],
    ["full-fledged", "成熟的, 充分发展的"],
    ["guru", "大师"],
    ["emergent", "新兴的, 紧急的"],
    ["ornate", "装饰华丽的"],
    ["magma", "岩浆"],
    ["noxious", "有害的"],
    ["gimbal lock", "万向节锁"],
    ["tandem", "串联"],
    ["extrude", "挤压"],
    ["haphazard", "偶然的, 随意的"],
    ["convex", "凸面的"],
    ["albedo", "反照率"],
    ["crevices", "裂缝"],
    ["subordinate", "下级的, 从属的"],
    ["pertain", "相关的"],
    ["hectic", "忙乱的"],
    ["agonize", "（使）极度痛苦"],
    ["puppeteer", "木偶师"],
    ["denote", "表示"],
    ["wack", "怪人"],
    ["proactive", "积极主动的"],
    ["altruistic", "利他的"],
    ["deplete", "耗尽"],
    ["refraction", "折射"],
    ["vitality", "活力, 生命力"],
    ["logistics", "物流"],
    ["syllabus", "教学大纲"],
    ["polygon", "多边形"],
    ["propagate", "传播"],
    ["notion", "概念"],
    ["presage", "预示"],
    ["spout", "喷口"],
    ["synopsis", "概要"],
    ["catapult", "弹射器"],
    ["morphing", "变形"],
    ["boffin", "专家, 科学家（俚语）"],
    ["fray", "争吵"],
    ["dodgy", "可疑的"],
    ["ample", "充足的"],
    ["allude to", "暗指"],
    ["sprite", "精灵"],
    ["atlas", "精灵图集, spritesheet"],
    ["effectively", "基本上就是..., basically"],
    ["entail", "蕴涵"],
    ["composite", "复合的"],
    ["dither", "抖动"],
    ["interleave", "交错"],
    ["palette", "调色板"],
    ["arbitrary", "人为的, 任意的"],
    ["artifacting", "伪影"],
    ["faux", "假的, 人造的"],
    ["crude", "粗糙的"],
    ["gist", "要点"],
    ["ubiquitous, omnipresent", "无处不在的"],
    ["tactile", "触觉的"],
    ["apt", "恰当的"],
    ["synonymous", "同义的"],
    ["fling", "抛"],
    ["die", "骰子"],
    ["disparate", "不同的"],
    ["fixture", "固定装置"],
    ["kinematic", "运动学的"],
    ["affix", "附加"],
    ["climatic", "气候的"],
    ["objectively", "客观地"],
    ["restitution", "恢复"],
    ["joint", "关节"],
    ["treads", "踏板"],
    ["inclined", "倾斜的"],
    ["pertinent", "相关的"],
    ["coaxial", "同轴的"],
    ["suffice to say", "可以说..."],
    ["rigid body", "刚体"],
    ["pinball", "弹球"],
    ["yield", "让..."],
    ["pitch", "俯仰"],
    ["yaw", "偏航"],
    ["polling", "轮询"],
    ["boilerplate", "模板"],
    ["caveat", "注意事项"],
    ["imposter", "冒名顶替者"],
    ["geometry", "几何体"],
    ["cue", "暗示"],
    ["spline", "样条线"],
    ["buoyancy", "浮力"],
    ["pontoon", "浮桥"],
    ["murkiness", "浑浊度"],
    ["caustics", "焦散"],
    ["ambient occlusion", "环境光遮蔽"],
    ["locomotion", "（生物体）运动"],
    ["translucent", "半透明"],
    ["decal", "贴花"],
    ["jolly", "欢乐的"],
    ["niggling", "琐碎的"],
    ["scalar", "标量"],
    ["eigenvalues", "特征值"],
    ["canonical", "标准的"],
    ["pare", "削减"],
    ["parallelogram", "平行四边形"],
    ["associativity", "关联性(结合性)"],
    ["orthonormal", "正交的"],
    ["commutative", "交换的"],
    ["applet", "小程序"],
    ["composing transforms", "组合变换"],
    ["reciprocal", "倒数"],
    ["corollary", "推论"],
    ["euler angles", "欧拉角"],
    ["quaternions", "四元数"],
    ["sanity check", "完整性检查"],
    ["trigonometry", "三角学"],
    ["jargon", "行话"],
    ["triad", "三元组"],
    ["yank", "猛拉"],
    ["designated", "指定的"],
    ["proposition", "命题"],
    ["mitigate", "减轻"],
    ["dislodge", "移位"],
    ["annealing", "退火"],
    ["applicable", "适用的"],
    ["decimal", "小数, 小数点"],
    ["interleave", "交错"],
    ["perceptron", "感知元"],
    ["outliers", "异常值"],
    ["holdout", "验证集"],
    ["suffice", "足够"],
    ["intricate", "复杂的"],
    ["plop", "放, 啪嗒声"],
    ["chronologically", "按时间顺序"],
    ["occlusions", "遮挡"],
    ["desaturate", "去饱和"],
    ["cheesy", "俗气的"],
    ["intensity", "强度"],
    ["tangent", "切线"],
    ["overhead view", "俯视图"],
    ["perspective projection", "透视投影"],
    ["focal plane", "焦平面"],
    ["frustum", "截锥体"],
    ["perturbed", "扰动的"],
    ["encompass", "包围"],
    ["discern", "辨别"],
    ["primitive", "图元"],
    ["stencil", "模板"],
    ["substitute", "替代"],
    ["uniform matrix", "均匀矩阵"],
    ["tessellation", "细分"],
    ["stride", "步长"],
    ["nuts and bolts", "螺母和螺栓"],
    ["diffuse", "散射"],
    ["specular", "镜面反射"],
    ["magenta", "品红"],
    ["advent", "到来"],
    ["glossy", "光滑的"],
    ["polished floor", "抛光之后的地板"],
    ["dielectric", "电介质"],
    ["quadratic", "二次的"],
    ["matte", "哑光的"],
    ["coarse", "粗糙的"],
    ["wood grain", "木纹"],
    ["bilinear", "双线性"],
    ["mipmap", "多级贴图"],
    ["brackets", "括号"],
    ["arbitrage", "套利"],
    ["trippy", "迷幻的"],
    ["taxonomy", "分类学"],
    ["ethos", "精华"],
    ["interreflections", "互相反射"],
    ["tinge", "色调"],
    ["subsequently", "随后"],
    ["hindsight", "后见之明"],
    ["manifestation", "表现"],
    ["barycentric", "重心的"],
    ["ellipsoid", "椭球体"],
    ["nevertheless", "尽管如此"],
    ["jitter", "抖动"],
    ["jaggies", "锯齿状"],
    ["film", "画布"],
    ["cull", "剔除"],
    ["ambient", "环境的"],
    ["finicky", "挑剔的"],
    ["nacho", "烤干酪辣味玉米片"],
    ["namely", "也就是..."],
    ["respectively", "分别"],
    ["elaborate", "阐述"],
    ["median", "中间值"],
    ["empirical", "经验的"],
    ["niche", "小众, 领域"],
    ["ecstatic", "欣喜若狂"],
    ["trivial", "琐碎的"],
    ["token", "代币, piece"],
    ["constituent", "组成的"],
    ["inaudible", "听不清的"],
    ["exhaustive", "详尽的"],
    ["fine-grained control", "细粒度控制"],
    ["inertia", "惯性"],
    ["quirks", "怪癖"],
    ["clumsy", "笨拙的"],
    ["infer", "推断"],
    ["lo and behold", "瞧！看！"],
    ["punctuation", "标点"],
    ["lingo", "行话"],
    ["pseudonymous", "匿名的"],
    ["decimal point", "小数点"],
    ["redeem", "兑换"],
    ["evident", "明显的"],
    ["schism", "分裂"],
    ["implication", "预兆"],
    ["siloed", "孤立的"],
    ["scarce", "稀缺的"],
    ["formulate", "构想"],
    ["recur", "再次发生"],
    ["convoluted", "复杂的"],
    ["admissible", "可接受的"],
    ["intractable", "难以处理的"],
    ["adversarial search", "对抗搜索"],
    ["verbose", "详细的"],
    ["deduce", "推导"],
    ["convolution", "卷积"],
    ["pooling", "汇集"],
    ["recurrent", "循环的"],
    ["modus ponens", "MP"],
    ["exclusive or", "异或"],
    ["inclusive or", "或"],
    ["entail", "蕴涵"],
    ["complimentary literals", "互补文字"],
    ["clause", "子句"],
    ["disjunction", "or"],
    ["inference by resolution", "消解推理"],
    ["quantifier", "量词"],
    ["distill", "提取"],
    ["counterfeit", "伪造(的)"],
    ["axiom", "公理"],
    ["contrived", "人为的"],
    ["heredity", "遗传"],
    ["logistic sigmoid", "逻辑S型函数"],
    ["rectified", "整流的"],
    ["circumvent", "规避"],
    ["epoch", "轮, round"],
    ["syntax", "语法"],
    ["briskly", "轻快地"],
    ["semantics", "语义"],
    ["determiner", "限定词"],
    ["prepositions", "介词"],
    ["corpus", "语料库"],
    ["wind up", "结束，..."],
    ["proportional to", "正比于..."],
    ["sentiment", "情绪"],
    ["tensor", "张量"],
    ["monetary", "货币的"],
    ["space shuttle", "航天飞机"],
    ["privilege", "特权/荣幸"],
    ["rendezvous", "会合"],
    ["low Earth orbit (LEO)", "近地轨道, 200 - 2000 km"],
    ["on-orbit", "在轨的"],
    ["interplanetary", "星际的"],
    ["trajectories", "轨迹"],
    ["spaceflight", "a voyage outside the Earth's atmosphere"],
    ["principally", "主要的, chief"],
    ["robotic missions", "机器人任务"],
    ["extravehicular", "舱外的"],
    ["on two occasions", "有两次"],
    ["emphasis", "重点"],
    ["radiation belt", "辐射带"],
    ["Lagrange points", "拉格朗日点"],
    ["propulsion", "推进力"],
    ["solar arrays", "太阳能电池阵列"],
    ["servicing mission", "维修任务"],
    ["burns", "点火"],
    ["maneuvers", "动作"],
    ["space vehicle", "太空飞行器"],
    ["capsule", "舱"],
    ["flight controller", "飞行控制员"],
    ["flight director", "飞行主管（高级飞行控制员）"],
    ["elementary", "初级"],
    ["mastery", "精通, 掌握"],
    ["mechanics", "力学"],
    ["extensively", "广泛地"],
    ["astronomy", "天文学"],
    ["celestial", "天体的, 天文的"],
    ["instrumentation", "仪器"],
    ["govern...", "控制"],
    ["rotation", "自转"],
    ["refracting telescope", "折射望远镜"],
    ["lenses", "透镜"],
    ["reflecting telescope", "反射望远镜"],
    ["spacecraft", "宇宙飞船"],
    ["the law of gravitation", "万有引力定律"],
    ["propel", "推进"],
    ["interplanetary space", "行星际空间"],
    ["visionary", "有远见的"],
    ["spacefaring", "航天的"],
    ["space flight", "航天"],
    ["resounding", "高亢"],
    ["suborbital", "亚轨道, around 100 km"],
    ["boundary of space", "Kármán line, 100 km"],
    ["orbital flight", "轨道飞行"],
    ["umbilical cord", "脐带"],
    ["propulsion system", "推进系统"],
    ["subsequent", "随后的"],
    ["high paced", "快节奏"],
    ["kerosene", "煤油"],
    ["liftoff", "升空"],
    ["splashdown", "splash, down"],
    ["striking", "引人注目的"],
    ["a logical choice", "一个合理的选择"],
    ["radical", "先进的"],
    ["rugged", "崎岖"],
    ["launchpad", "发射台"],
    ["orbiter", "轨道飞行器"],
    ["silica tile", "硅砖"],
    ["instrument", "仪器"],
    ["antennas", "天线"],
    ["truss", "桁架"],
    ["the outer space treaty", "外层空间条约"],
    ["orbital velocity", "轨道速度"],
    ["parties", "缔约方"],
    ["signatories", "签署方"],
    // ["Pretty much like for Antarctica, there can be no national appropriation by claim of sovereignty on any part of a celestial body."],
    ["debris", "碎片"],
    ["so as to", "to"],
    ["adverse changes", "不利的变化"],
    ["adopt", "采取（措施）"],
    ["graveyard", "v. put something into graveyard..."],
    ["in line with", "一致..."],
    ["stipulate", "规定, formulate"],
    ["asteroid", "小行星"],
    ["extraterrestrial", "外星的"],
    ["operate", "运营"],
    ["logistic resupply (to)...", "后勤补给"],
    ["troposphere", "对流层 6 - 20 km"],
    ["stratosphere", "平流层 50 km"],
    ["mesosphere", "中间层 85 km"],
    ["thermosphere", "热层 690 km"],
    ["exosphere", "外逸层 10,000 km"],
    ["telemetry data", "遥测数据"],
    ["constellation", "星座,（太空飞行）具有相同用途的一组卫星"],
    ["false color image", "伪彩图像"],
    ["Earth crust", "地壳"],
    ["discipline", "学科"],
    ["flux", "通量"],
    // ["Space weather is a consequence of a variation in the flux of particles in the solar wind that has an influence on the general conditions around the Earth."],
    ["physiology", "生理学"],
    ["interstellar", "星际的"],
    ["serviceable", "可维修的"],
    ["a very large catalog of...", "大量的..."],
    ["stellar system", "恒星系统"],
    ["proper motion", "自行"],
    ["radial velocity", "径向速度"],
    ["parallax", "视差"],
    ["Magellanic clouds", "麦哲伦星云"],
    ["coronagraph", "日冕仪"],
    ["constitute", "构成"],
    ["rover", "漫游者"],
    ["nucleus", "（彗星的）核心"],
    ["perihelion", "近日点"],
    ["parabola", "抛物线"],
    ["air drag", "空气阻力"],
    ["95 metric tons", "公吨"],
    ["vehicle", "载具"],
    ["super heavy-lift launch vehicles", "超重型运载火箭 > 50 t payload"],
    ["spaceports", "太空港"],
    ["oscillations", "振荡"],
    ["elasticity", "弹性"],
    ["wither away...", "远离..."],
    ["a helicoidal shape", "螺旋形状"],
    ["centrifuge", "离心机"],
    ["profile", "模式, 曲线"],
    ["longitudinal", "纵向"],
    ["trampoline", "蹦床"],
    ["vestibular", "前庭的"],
    ["exoplanet", "系外行星"],
    ["geysers", "间歇泉"],
    ["adversity", "逆境"],
    ["new moon", "新月"],
    ["crescent", "新月"],
    ["angular", "角度的"],
    ["facultative", "可选的"],
    ["with respect to", "对于..."],
    ["subject to", "受到..."],
    ["exert", "施加"],
    ["expel", "排出"],
    ["throttle", "n. 节流阀, 油门, v. control (an engine or vehicle) with a throttle"],
    ["negligible", "微不足道的"],
    ["derivative", "导数"],
    ["momentum", "动量 kg·m/s"],
    ["angular momentum", "角动量"],
    ["volume", "体积"],
    ["top", "陀螺"],
    ["displacement", "位移"],
    ["analogue", "类似物"],
    ["conservation laws", "守恒定律"],
    ["potential energy", "势能"],
    ["specific energy/massic energy", "energy per unit mass, 比能, 每单位质量所具有的能量 J/kg, m²/s²"],
    ["kinetic energy", "动能"],
    ["electrical field", "电场"],
    ["friction", "摩擦"],
    ["velocity", "速度 m/s"],
    ["acceleration", "加速度 m/s²"],
    ["newton", "牛顿 kg·m/s²"],
    ["cylinder", "圆柱"],
    ["waning moon", "残月"],
    ["elapse", "过去, 流逝, pass by"],
    ["calculus", "微积分"],
    ["secant line", "割线, the line connecting two points on a curve"],
    ["tangent line", "切线"],
    ["in a nutshell", "简而言之"],
    ["tackle", "解决（问题）"],
    ["revenue", "收入"],
    ["premier", "顶级的"],
    ["the Monaco Grand Prix", "摩纳哥大奖赛"],
    ["conglomeration", "集合体"],
    ["unravel", "解释"],
    ["skid (off, over)", "打滑"],
    ["pit crew", "维修站工作人员"],
    ["esteemed", "受人尊敬的"],
    ["inadequate", "不足的"],
    ["grip", "抓地力"],
    ["hairpin turns", "发卡弯"],
    ["infamous", "臭名昭著"],
    ["dash", "破坏"],
    ["lift", "升力"],
    ["impart", "传, pass on"],
    ["driveshaft", "传动轴"],
    ["axles", "车轴"],
    ["normal force", "法向力"],
    ["normal reaction", "法向反作用力"],
    ["sheer", "陡峭的"],
    ["a visceral feeling", "一种发自内心的感觉"],
    ["beeline", "straight line"],
    ["recap", "回顾"],
    ["calamity", "灾难"],
    ["quandary", "困惑"],
    ["conundrum", "难题"],
    ["plot", "绘图"],
    ["Out-of-this-World", "超凡脱俗的"],
    ["analogy", "类比"],
    ["curvature", "曲率"],
    ["tin foil", "锡纸"],
    ["for sake of", "to"],
    ["argument", "论证"],
    ["graze", "掠过"],
    ["recipe", "方法"],
    ["difference quotient", "差商"],
    ["plummeting", "直线下降的"],
    ["hold off", "等一下"],
    ["make ... a snap", "轻而易举"],
    ["skeuomorphic", "拟物化的"],
    ["cosmopolitan", "大都会"],
    ["extensive", "广泛的"],
    ["bioreactors", "生物反应器"],
    ["nudge", "轻推"],
    ["critical point", "临界点"],
    ["maxima", "极大值"],
    ["minima", "极小值"],
    ["extremum", "极值"],
    ["punchline", "妙处"],
    ["whittle down", "削减"],
    ["second derivative test", "二阶导数检验"],
    ["saddle point", "鞍点"],
    ["placeholder", "占位符"],
    ["jerk", "加加速度"],
    ["ballpark", "球场"],
    ["Taylor series", "泰勒级数"],
    ["faucet", "龙头"],
    ["catchy", "朗朗上口的"],
    ["shore up", "支撑"],
    ["polynomials", "多项式"],
    ["power", "幂"],
    ["aside", "旁白"],
    ["difference quotient", "差商"],
    ["numerator", "分子"],
    ["sought-after", "被追捧的"],
    ["at long last", "最后, finally"],
    ["quotient", "商"],
    ["rational functions", "有理函数"],
    ["in a loose sense", "广义上"],
    ["rim", "边缘"],
    ["handy", "趁手的"],
    ["sideline", "边线"],
    ["bird's-eye view", "鸟瞰图"],
    ["near", "v. 接近"],
    ["breakaway", "突破"],
    ["fraction", "分数"],
    ["denominator", "分母"],
    ["goal", "球门"],
    ["groundwork", "基础"],
    ["so long as", "只要"],
    ["graft", "嫁接"],
    ["scoop off", "挖掉"],
    ["Riemann sum", "黎曼和"],
    ["rug", "小地毯"],
    ["anatomy", "剖析"],
    ["definite integral", "定积分"],
    ["integral, integration", "n. integrate, 累加, 积分"],
    ["integrand", "积函数"],
    ["elongated", "拉长的"],
    ["subinterval", "子区间"],
    ["endpoint", "端点"],
    ["squared away", "解决了"],
    ["In broad strokes", "概括地说"],
    ["term", "项"],
    ["rectangle", "矩形"],
    ["versatile", "通用的"],
    // ["One of the deepest theorems in calculus says that derivatives and integrals are two sides of the same coin."],
    ["deepest", "深奥的"],
    ["theorem", "定理"],
    ["voyage", "旅程"],
    ["fission", "裂变"],
    ["fusion", "聚变"],
    ["watered-down", "淡化的"],
    ["intrepid", "勇敢的"],
    ["planar", "平面的"],
    ["net change theorem", "净变化定理"],
    ["take ... word for it", "相信...的话"],
    ["the fundamental theorem", "基本定理"],
    ["in action", "in operation"],
    ["constant of integration", "积分常数"],
    ["arithmetic", "四则运算"],
    ["bear on", "解决"],
    ["swat", "扑打"],
    ["rest", "n. 静止"],
    ["frontier", "边境"],
    ["pesky", "讨厌的"],
    ["differential equations", "微分方程"],
    ["Gabriel's horn", "加布里埃尔的号角"],
    ["paradoxical", "自相矛盾的"],
    ["surface of revolution", "旋转表面"],
    ["line segment", "线段"],
    ["differentiate, differential", "v., n. 微分"],
    ["make sense of...", "理解"],
    ["regular polygon", "正多边形"],
    ["carve up", "分割"],
    ["congruent right triangles", "全等直角三角形"],
    ["inscribe", "内切"],
    ["equilateral triangle", "等边三角形"],
    ["sequence", "序列"],
    ["cosmic rays", "宇宙射线"],
    ["radioactive", "放射性的"],
    ["replenish", "补充"],
    ["shuffled off its mortal coil", "摆脱了凡人的束缚"],
    ["proton", "质子"],
    ["exponential decay", "指数衰减"],
    ["logistic sequence", "逻辑序列"],
    ["indefinitely", "无限期地"],
    ["content ... with", "满足于"],
    ["identity", "恒等式"],
    ["infinite sum", "无限和"],
    ["Tower of Lire", "里拉塔"],
    ["topmost", "最上面的"],
    ["overhang", "（延伸而出）悬挂"],
    ["stroke", "抚摸, caress"],
    ["awed", "敬畏的"],
    ["talent scout", "星探"],
    ["poised at", "在..."],
    ["pitch (to)", "提出"],
    ["meager", "微薄的"],
    ["pun", "双关语"],
    ["grand finale", "大结局"],
    ["mileage", "进展"],
    ["entry-level", "入门级的"],
    ["pizzeria", "比萨店"],
    ["infinitesimal", "无穷小"],
    ["plausible", "可信的, 似是而非的"],
    ["standard kinematics equation", "标准运动学方程"],
    ["projectile", "抛射物"],
    ["angular kinematics", "角运动学"],
    ["racetrack", "赛道"],
    ["radians", "弧度"],
    ["modulo", "mod, 模"],
    ["NASCAR", "全美改装车竞赛"],
    ["time trial", "计时赛"],
    ["crux", "关键"],
    ["oil slick", "浮油"],
    ["compositions of functions", "函数复合"],
    ["squared", "平方"],
    ["notation", "表示"],
    ["spells", "咒语"],
    ["potions", "药水"],
    ["terminology", "术语"],
    ["vertical line test", "垂直线测试"],
    ["codomain", "协域"],
    ["image", "映射"],
    ["composite function, composition", "复合函数"],
    ["inverse, inverse function", "反函数"],
    ["invertibility", "可逆性"],
    ["horizontal line test", "水平线测试"],
    ["inverse trigonometric functions", "反三角函数"],
    ["interchange", "交换"],
    ["right angle triangles", "直角三角形"],
    ["hypotenuse", "斜边"],
    ["Pythagoras theorem", "毕达哥拉斯定理"],
    ["bedrock", "基岩"],
    ["jump", "跃变"],
    ["kink", "拐点"],
    ["exponential", "指数的"],
    ["implicit functions", "隐式函数"],
    ["folium of Descartes", "笛卡儿叶形线"],
    ["cardioid", "心形线"],
    ["leverage", "利用"],
    ["singularity", "奇点"],
    ["jokingly", "开玩笑地"],
    ["rile up", "激怒"],
    ["put ... at ease", "让...放心"],
    ["rigorous", "严格的"],
    ["approximation", "近似"],
    ["linearization", "线性化"],
    ["decimal expansion", "小数"],
    ["scheme", "方案, plan"],
    ["differential", "微小差别, 差分/微分"],
    ["gadget", "小工具"],
    ["propagation of error", "误差传播"],
    ["approximate absolute error", "近似绝对误差"],
    ["approximate relative error", "近似相对误差"],
    ["Taylor polynomial", "泰勒多项式"],
    ["factorial", "阶乘, 3!"],
    ["five places of decimals", "小数点后五位"],
    ["Taylor series", "泰勒序列/泰勒级数"],
    ["Taylor's Inequality", "泰勒不等式"],
    ["rest mass", "静息质量"],
    ["special relativity", "狭义相对论"],
    ["horizontal asymptotes", "水平渐近线"],
    ["growth rates", "增长率"],
    ["equilibrium", "平衡 (plural: equilibria)"],
    ["damped oscillation", "阻尼振荡"],
    ["amplitude", "magnitude, 大小"],
    ["preliminary", "初步的"],
    ["evolution", "演化"],
    ["manifests as...", "表现为..."],
    ["concentration", "浓度"],
    ["frame", "build, establish, 修建, 建立"],
    ["brass tacks", "黄铜钉"],
    ["proclaim", "宣布"],
    ["standard limits", "标准极限"],
    ["the dominant term method", "主导项方法"],
    ["hierarchy of dominance", "主导层级"],
    ["coefficient", "系数"],
    ["squeeze theorem/sandwich theorem", "挤压定理/三明治定理"],
    ["envelope", "cage, 笼"],
    ["mutatis mutandis", "changing [only] those things which need to be changed, 稍微改改就可以"],
    ["springboard", "跳板"],
    ["sporadically", "零星地"],
    ["remark", "n. v., 注释, 评论"],
    ["signed area", "矢量面积"],
    ["disk", "圆盘"],
    ["elaborate", "adj. very detailed and complicated"],
    ["refrain from", "避免"],
    ["kick things up a notch", "让事情更上一层楼"],
    ["anti-derivative", "反导数"],
    ["Fresnel function", "菲涅尔函数"],
    ["peculiar", "strange, 奇特的"],
    ["ins and outs", "来龙去脉"],
    ["subtlety", "微妙"],
    ["facilitate", "promote, 促进"],
    ["bread and butter", "基石"],
    ["in a way", "from some points of view"],
    ["culmination", "高潮, climax"],
    ["endeavor", "work hard/hard work"],
    ["gauge", "初始值"],
    ["initial value problems", "初始值问题"],
    ["solvent", "溶剂"],
    ["solution", "溶液"],
    ["direction fields", "方向场"],
    ["autonomous equation", "自治方程"],
    ["separable differential equations", "可分离微分方程"],
    ["factorize", "因式分解"],
    ["linear differential equations", "线性微分方程"],
    ["integrating factor", "积分因子"],
    ["ansatz", "guessing"],
    ["indispensable", "不可或缺的"],
    ["subscripts", "下标"],
    ["superscripts", "上标"],
    ["summation", "累加"],
    ["read off (information)", "读取"],
    ["qualitative", "定性的"],
    ["level headed", "头脑冷静的, cool-headed"],
    ["maximal domain", "最大域"],
    ["practical domain", "实用的域"],
    ["Cartesian coordinate system", "笛卡尔坐标系"],
    ["level curve", "等高线"],
    ["contour", "轮廓"],
    ["level surface", "等值面"],
    ["paraboloid", "抛物面"],
    ["partial derivatives", "分导数"],
    ["d", "dee, total derivative"],
    ["∂", "del, partial derivative"],
    ["passage", "通道"],
    ["Clairaut's theorem", "克莱罗定理"],
    ["evaluate", "评估"],
    ["begs... (the question)", "引出了"],
    ["quest", "探索 - exploration, 追寻 - pursue"],
    ["oversight", "疏忽, negligence"],
    ["directional derivatives", "方向导数"],
    ["sinusoidal", "正弦曲线的"],
    ["cross-section", "横截面"],
    ["normal form", "法线形式, ax + by = c"],
    ["preempt", "抢先"],
    ["transversal", "横向的"],
    ["cusp", "spike, 尖点"],
    ["inconclusive", "不确定的"],
    ["Hessian matrix", "黑塞矩阵"],
    ["eigenvalues", "特征值"],
    ["streamlined", "精简的"],
    ["legend", "图例"],
    ["interior", "adj. n., 内部（的）"],
    ["criterium", "criterion, 标准, criteria (plural)"],
    ["in a row", "adv. 连续"],
    ["lamina", "薄片"],
    ["a loaf of bread", "一条面包"],
    ["oblique line", "斜线"],
    ["hyperbola", "双曲线"],
    ["isosceles", "等腰的"],
    ["circular symmetries", "圆对称性"],
    ["arc length", "弧长"],
    ["Jacobian", "雅可比因子"],
    ["iterated integral", "迭代积分"],
    ["tetrahedron", "四面体"],
    ["rotational symmetries", "旋转对称性"],
    ["hemisphere", "半球"],
    ["longitude-latitude coordinates system", "经纬度坐标系"],
    ["mine shaft", "矿井"],
    ["spherical symmetries", "球对称性"],
    ["spinning top", "陀螺"],
    ["scone", "司康饼"],
    ["treatise", "论述, study"],
    ["scientific notation", "科学计数法"],
    ["round ...", "四舍五入"],
    ["significant digits/figures", "有效数字"],
    ["adequate", "足够的"],
    ["take about ...", "考虑一下..., consider"],
    ["well-versed", "精通的"],
    ["algebra", "运算结构学, 代数"],
    ["kinematics", "运动学"],
    ["motion", "运动"],
    ["slate board", "板岩板"],
    ["in motion", "在运动的"],
    ["plainspoken", "直言不讳的"],
    ["electrons", "电子"],
    ["protons", "质子"],
    ["neutrons", "中子"],
    ["soak in...", "savor, 沉浸, 品味"],
    ["throw in the towel", "认输"],
    ["joule", "焦耳 N·m, kg·m²/s²"],
    ["teeny bit", "一点点"],
    ["work", "功, W = F(vec) · Δr(vec), kg·m²/s²"],
    ["street definition", "街头定义"],
    ["power", "\"how fast you are working\", P = F(vec) · v(vec),"],
    ["ramp", "坡道"],
    ["mechanical energy", "力能, 机械能"],
    ["gravitation", "引力"],
    ["gravity", "重力"],
    ["momentum", "P(vec) = mv(vec), 动量"],
    ["repulsive", "<->"],
    ["sterile", "无菌的"],
    ["Large Hadron Collider (LHC)", "大型强子对撞机"],
    ["Higgs", "希格斯粒子"],
    ["splat", "split"],
    ["contemplative", "沉思的"],
    ["exhaust", "排气"],
    ["pendulum", "钟摆"],
    ["conserved", "守恒的"],
    ["repulsive force", "斥力"],
    ["artistry", "艺术"],
    ["barge", "驳船"],
    ["amphitheater", "露天剧场"],
    ["expend", "花费"],
    ["nirvana", "涅槃"],
    ["indulge", "放纵"],
    ["dojo", "道场"],
    ["uniform circular motion", "匀速圆周运动"],
    ["characterize", "formalize"],
    ["centripetal (center seeking) acceleration", "向心加速度"],
    ["circumference", "圆周, 周长"],
    ["tangential", "切向的"],
    ["radial", "径向的"],
    ["radii", "半径, radius (plural.)"],
    ["extended object", "拉伸对象"],
    ["tricky", "棘手的"],
    ["spokes", "辐条"],
    ["rotational kinetic energy", "旋转动能"],
    ["moment/moment of inertia", "惯性力矩"],
    ["unwind", "展开"],
    ["prism", "棱柱"],
    ["azimuthal angle, azimuth", "方位角"],
    ["torque", "扭矩, a force around an axis"],
    ["hinge", "pivot, 枢"],
    ["gravitas", "庄重"],
    ["Atwood Machine", "阿特伍德机器"],
    ["redux", "adj. n., a theme or topic redone, restored, brought back, or revisited"],
    ["pulley", "滑轮"],
    ["envision", "构想"],
    ["strip lights", "灯带"],
    ["cycloid", "摆线"],
    ["Mm, foreshadowing.", "嗯，有预感。"],
    ["pun", "双关语"],
    ["timeless", "永恒的"],
    ["revolution", "旋转（一周）"],
    ["precess(ion)", "Falling with style. 绕轴旋转"],
    ["fidget", "坐立不安"],
    ["cubicle", "小隔间"],
    ["gyroscope", "陀螺仪"],
    ["gimbal mount", "万向架"],
    ["provincial", "狭隘的"],
    ["apparatus", "仪器"],
    ["moose", "驼鹿"],
    ["elliptical orbits", "椭圆轨道"],
    ["semi-major axis", "半长轴, long radius"],
    ["semi-minor axis", "半短轴, short radius"],
    ["eccentricity", "偏心率"],
    ["Halley's Comet", "哈雷彗星"],
    ["gravitational field", "引力场"],
    ["gravity well", "重力井"],
    ["escape velocity", "逃逸速度"],
    ["event horizon", "事件视界"],
    ["idyllic", "田园诗般的"],
    ["contemporaries", "同时代的人"],
    ["separation", "距离"],
    ["take a stab at...", "尝试一下"],
    ["endow", "赋予"],
    ["depict", "描绘"],
    ["astrology", "占星学"],
    ["inertial frame", "惯性系"],
    ["conservative forces", "\"they dont waste energy\" - gravitational, spring forces, electrostatic, 守恒力"],
    ["dissipative forces", "耗散力"],
    ["geosynchronous orbit, GSO", "地球同步轨道"],
    ["geostationary orbit, GEO", "地球静止轨道/地球赤道同步轨道"],
    ["geostationary satellite", "地球静止卫星"],
    ["molecule", "分子"],
    ["argon", "氩气"],
    ["tropopause", "对流层顶"],
    ["degrees centigrade/celsius", "摄氏度"],
    ["ozone region", "臭氧区"],
    ["airfoil", "机翼"],
    ["weightlessness", "失重"],
    ["perturbing forces", "扰动力"],
    ["atmospheric drag", "大气阻力"],
    ["microgravity", "微重力"],
    ["braking force", "制动力"],
    ["residual", "剩余的"],
    ["tethered", "拴着的"],
    ["airglow", "air glows"],
    ["photoionization", "光电离"],
    ["de-excitation", "the process by which an atom, molecule, or nucleus releases energy to return to a lower energy state after having been in an excited state."],
    ["luminescence", "发光"],
    ["Crux/the Southern Cross", "南十字星"],
    ["geomagnetic field", "地磁场"],
    ["radiation (or Van Allen) belts", "辐射（范艾伦）带"],
    ["magnetosphere", "磁层"],
    ["charge particles", "带电粒子"],
    ["predominantly", "主要地, mainly"],
    ["aurora", "极光"],
    ["northern lights/aurora borealis", "北极光"],
    ["southern lights/aurora australis", "南极光"],
    ["excitation", "激化"],
    ["oval", "椭圆形"],
    ["Orion", "猎户座"],
    ["sunspots", "太阳黑子"],
    ["solar radio flux", "太阳辐射通量"],
    ["order", "数量级"],
    ["irradiance", "辐照度, W/m²"],
    ["diminished", "减少的"],
    ["variational", "变化的"],
    ["quadratic", "二次的"],
    ["placebo", "没有关联的"],
    ["turbulence", "湍流"],
    ["granularity", "粒度"],
    ["flares", "耀斑"],
    ["Jupiter", "木星"],
    ["prominence", "日珥"],
    ["coronal mass ejections", "日冕物质抛射"],
    ["heliosphere", "日光层"],
    ["occult", "遮蔽"],
    ["toroidal", "环形的"],
    ["bolometric flux", "辐射热通量"],
    ["plasma", "等离子体"],
    ["gust", "阵风"],
    ["(galactic) cosmic rays", "（银河）宇宙射线"],
    ["South Atlantic Anomaly (SAA)", "南大西洋异常"],
    ["ocular globes", "眼球"],
    ["RAD", "= Radiation Absorbed Dose = Amount of energy absorbed, 0.01 J/kg"],
    ["REM", "= Roentgen Equivalent Man = RAD * Q"],
    ["Q", "= quality factor"],
    ["Sievert", "= Sv = 100 REM"],
    ["ionosphere", "电离层"],
    ["ultraviolet", "10 - 400 nm, n. v., 紫外线（的）"],
    ["visible light", "400 - 700 nm, 可见光"],
    ["infrared", "700 nm - 0.1 cm, n. v., 红外线（的）"],
    ["astronomical unit (AU)", "天文单位, the average distance between the Earth and the Sun, 149,597,870.7 (≈ 150 million) km"],
    ["α (solar absorptivity)", "太阳能吸收率"],
    ["degradation", "下降"],
    ["(electrical) discharges", "放电"],
    ["sun cream", "防晒霜"],
    ["solar constant", "solar electromagnetic radiation power per unit area, 1361 W/m²"],
    ["thermoelectric generators", "热电发电机"],
    ["gaseous planet", "气态行星"],
    ["epoxy", "环氧树脂"],
    ["coating", "涂层"],
    ["fiery", "火热的"],
    ["perigee", "近地点"],
    ["apogee", "远地点"],
    ["ballistic coefficient", "弹道系数"],
    ["space debris", "空间碎片"],
    ["high-gain antenna", "高增益天线"],
    ["Sun-synchronous orbit altitude", "太阳同步轨道高度"],
    ["iridium", "铱"],
    ["micrometeoroids and orbital debris (MMOD)", "微流星体和轨道碎片"],
    ["meteoroids", "small, rock-like remnants usually from comets or asteroids that are found in outer space. 流星体"],
    ["meteors", "the visible paths or streaks of light produced when a meteoroid enters the Earth's atmosphere and heats up due to friction with air molecules. 流星"],
    ["meteorites", "meteoroids that survive their passage through the Earth's atmosphere and strike the Earth's surface. 陨石"],
    ["comets", "icy bodies that orbit the sun, exhibit visible atmospheres and sometimes tails. 彗星"],
    ["asteroids", "larger, rock and metal bodies that orbit the Sun, mostly found in the asteroid belt between Mars and Jupiter. 小行星"],
    ["Cretaceous-Paleogene extinction", "白垩纪-古近纪灭绝"],
    ["peninsula", "半岛"],
    ["devise", "设计, design"],
    ["catalog", "目录"],
    ["insulation", "绝缘"],
    ["brittle", "脆的, crisp, fragile"],
    ["myriad", "无数"],
    ["laser ranging sensors", "激光测距传感器"],
    ["remediation", "补救措施"],
    ["mitigation", "减缓措施"],
    ["mission profile", "任务简介"],
    ["phasing maneuvers", "定相机动, phase - adjust so as to be in a synchronized condition"],
    ["intent", "意图, intention"],
    ["rendezvous", "n. v., 会合"],
    ["demise", "灭亡"],
    ["alleviate", "减轻, mitigate"],
    ["defunct", "n. v., dead, 死人"],
    ["initiative", "倡议"],
    ["aerospace", "atmosphere and outer space"],
    ["implications", "影响"],
    ["clipper", "快船"],
    ["orbital mechanics", "轨道力学"],
    ["gravitational well", "重力井"],
    ["dynamics of space flight", "太空飞行动力学"],
    ["homogeneous", "同质的, 均匀的"],
    ["thrust-to-weight ratio", "推重比"],
    ["icicle", "冰柱"],
    ["transfer velocity", "转移速度"],
    ["harpoon", "鱼叉"],
    ["afloat", "漂浮的"],
    ["centrifugal force", "离心力"],
    ["sidereal day", "恒星日"],
    ["apsis (plural. apsides)", "(from Ancient Greek ἁψίς (hapsís) 'arch, vault') 端点, point in elliptical orbit when a body is closest or furthest from the sun"],
    ["periapsis", "近点"],
    ["apoapsis", "远点"],
    ["true anomaly, θ", "The angle between the direction of the periapsis from the central body to the radius vector to the spacecraft or the planet."],
    ["ε, specific orbital energy (or vis-viva energy)", "energy of the orbit motion, per unit mass"],
    ["flight path angle", "航迹角"],
    ["main engine cutoff (shutdown)", "主发动机关闭"],
    ["powered ascent", "动力上升"],
    ["orbit insertion", "轨道插入"],
    ["posi-grade burn", "正向点火"],
    ["eccentric anomaly, E", "The angle between the periapsis vector and an projected object's (onto the auxiliary circle) direction vector."],
    ["transcendental equation", "超越方程"],
    ["geocentric-inertial coordinate system", "地心惯性坐标系"],
    ["vernal (spring) equinox", "春分点"],
    ["heliocentric", "日心的"],
    ["celestial pole", "天极"],
    ["plane of the ecliptic", "日地轨道平面"],
    ["ascending node, descending node", "上升点, 下降点"],
    ["transit", "过境, 通过, pass"],
    ["meridian", "经线"],
    ["Gregorian days", "公历日"],
    ["Julian days", "朱利安日"],
    ["ordinal", "顺序的"],
    ["sidereal", "adj. n. 恒星, stellar"],
    ["the Tropic of Cancer", "北回归线"],
    ["heavenly", "celestial"],
    ["celestial hemisphere", "天半球"],
    ["Britannica", "大英百科全书"],
    ["thistle", "蓟"],
    ["pro(posi)grade/retrograde maneuver", "顺行/逆行机动"],
    ["lateral speed", "横向速度"],
    ["barometer", "晴雨表, 气压计"],
    ["biome", "生物群落"],
    ["ablate", "消融, wear away (something) through erosion, melting, or vaporization"],
    ["oxidizer", "氧化剂"],
    ["fin", "鳍"],
    ["heading", "航向"],
    ["attitude", "姿态, the orientation of a vehicle relative to the horizon, direction of motion, other objects, etc."],
    ["whip out past the Moon", "掠过月球"],
    ["topography", "terrain, 地形"],
    ["highlands", "高地"],
    ["crux", "key, 关键"],
    ["... in the homestretch", "最后冲刺"],
    ["consortium", "联盟, an association of companies (or non-commercial institutions or organizations) for some definite purpose"],
    ["Vega", "织女星"],
    ["directorate", "理事会, 董事会"],
    ["motorway", "highway, 高速公路"],
    ["sublimate", "升华"],
    ["denomination", "面值"],
    ["orbiter complex", "轨道飞行器综合体"],
    ["Hohmann transfer", "霍曼转移"],
    ["nodal regression/progression", "节点后移/前移"],
    ["Sun-synchronous orbits", "太阳同步轨道"],
    ["line of nodes", "节点线, the intersection of the object's orbital plane with the plane of reference, and runs between the ascending and descending nodes"],
    ["wonky", "古怪的"],
    ["petal", "花瓣"],
    ["congregation", "set, 组"],
    ["cupola", "a small viewing window in the form of a dome for looking over the train/environment"],
    ["periscope", "潜望镜"],
    ["star tracker", "星追踪器"],
    ["fuselage", "机身"],
    ["port side", "左舷"],
    ["starboard", "右舷"],
    ["aft", "adj. adv., （朝向）船尾"],
    ["phase angle", "相位角"],
    ["wobble", "摇晃"],
    ["engrave", "雕刻"],
    ["interplanetary trajectories", "行星际航线"],
    ["parking orbit", "停车轨道"],
    ["sphere of influence (SOI)", "the spherical region where a planet dominate the orbits of surrounding objects such as moons"],
    ["hyperbolic excess velocity", "双曲超速度"],
    ["departure velocity", "出发速度"],
    ["implication", "meaning, 意义"],
    ["arc", "curve, 弧线"],
    ["impact parameter", "撞击参数"],
    ["in transit towards...", "正在前往..."],
    ["minor", "辅修"],
    ["aerodynamic braking", "空气动力制动"],
    ["aerocapture", "大气捕获"],
    ["coast", "v. 滑行, glide"],
    ["aerobraking", "大气制动"],
    ["aeroentry", "大气进入"],
    ["slingshot maneuvers", "gravity assist, flyby, 引力弹弓机动"],
    ["conic section", "圆锥曲线"],
    ["cryogenic", "低温的"],
    ["schematic", "示意图"],
    ["xenon discharge", "氙气放电"],
    ["delta wing", "三角翼"],
    ["expedition", "远征"],
    ["rudimentary", "preliminary, 初级的"],
    ["appendage", "附属物"],
    ["radioisotope thermal generators", "放射性同位素热发生器"],
    ["tether", "绳索"],
    ["chronology", "时间表"],
    ["tomography", "断层扫描"],
    ["jettison", "v. n., 抛弃"],
    ["refurbishment", "翻新"],
    ["rear view", "后视图"],
    ["undertaking", "工程"],
    ["novelty", "新奇"],
    ["compartment", "隔间, 舱"],
    ["airliner", "客机"],
    ["beef stroganoff", "俄式牛柳丝"],
    ["don", "v., wear"],
    ["bulkhead", "舱壁"],
    ["sill", "槛"],
    ["velcro patches", "尼龙搭扣贴片"],
    ["hasselblad camera", "哈苏相机"],
    ["pallet", "托盘"],
    ["conceive", "构想"],
    ["intervene", "干预"],
    ["chevron", "a shape like a (upside-down) “V”"],
    ["terminator, twilight zone", "晨昏线"],
    ["berth", "停泊, 泊位"],
    ["zenith", "顶点, apex"],
    ["nadir", "最低点"],
    ["extravehicular activity (EVA)", "载具外活动"],
    ["visor", "面罩"],
    ["Extravehicular Mobility Unit (EMU)", "载具外活动单元"],
    ["Manned Maneuvering Unit (MMU)", "单人机动单元"],
    ["egress", "出口"],
    ["bulky", "笨重的"],
    ["dexterous", "灵巧的"],
    ["cavity", "空腔"],
    ["aerobatics", "特技飞行"],
    ["In-Situ Resource Utilization (ISRU)", "就地资源利用"],
    ["excursion", "游览"],
    ["mundane", "平凡的"],
    ["singular", "奇特的"],
    ["lucrative", "有利可图的"],
    ["hammock", "吊床"],
    ["succinct", "简洁的"],
    ["encampment", "营地"],
    ["slew", "to turn (something, such as a telescope or a ship's spar) about a fixed point that is usually the axis"],
    ["end table", "茶几"],
    ["forest axe", "森林斧"],
    ["pickaxe", "十字镐"],
    ["recurve crossbow", "反曲弩"],
    ["galore", "adj. n. 丰富"],
    ["clutter", "杂物"],
    ["railing", "栏杆"],
    ["scarecrow", "稻草人"],
    ["bungalow", "平房"],
    ["pavilion", "亭子"],
    ["detached garage", "独立车库"],
    ["spark plug", "火花塞"],
    ["raspberry", "树莓"],
    ["foe", "敌人"],
    ["mantle", "攀爬"],
    ["hurdle", "翻越"],
    ["commerce", "连接"],
    ["llama", "骆驼"],
    ["vine", "藤蔓"],
    ["mesa", "台地"],
    ["prowl around", "徘徊"],
    ["cultivate", "培育"],
    ["loom", "织布机"],
    ["critter", "小动物"],
    ["ruby", "红宝石"],
    ["stow", "存放"],
    ["archaic", "古老的"],
    ["conversely", "反过来"],
    ["crumpet", "松饼"],
    ["flimsy", "脆弱的"],
    ["immaculate", "完美无瑕的"],
    ["cohort", "A group of people supporting the same thing or person."],
    ["ad hoc", "dedicated"],
    ["articulate", "adj., expressing oneself readily, clearly, and effectively"],
    ["isosurface", "等值面"],
    ["temporal", "时间的"],
    ["artifact", "人造物"],
    ["copywriter", "撰稿人"],
    ["oscilloscope", "示波器"],
    ["loupe", "放大镜"],
    ["surreal", "超现实的"],
    ["latent space", "潜在空间"],
    ["orthodox", "正统的"],
    ["foolhardy", "蛮干的"],
    ["churn", "弃游"],
    ["retention", "The act of retaining or something retained."],
    ["demographic", " a collection of people sharing a value for a certain demographic criterion"],
    ["spatial-temporal", "时空的"],
    ["molten map", "熔融图"],
    ["semaphore", "信号量"],
    ["dormant", "休眠的"],
    ["monolithic", "一体的"],
    ["novice", "新手"],
    ["scree plot", "A line plot of the eigenvalues of factors or principal components in an analysis."],
    ["reciprocal", "双向的"],
    ["obscure", "模糊的"],
    ["discrepancy", "差异"],
    ["reminiscent", "adj. Suggestive of an earlier event or times."],
    ["susceptible to, prone to", "易受影响的"],
    ["ensemble", "n. v. 合奏"],
    ["nuance", "细微差别"],
    ["wacky", "古怪的"],
    ["fiddly", "繁琐的"],
    ["coarser", "较粗的"],
    ["lattice", "格子"],
    ["fractals", "分形"],
    ["taxonomies", "分类法"],
    ["mullet", "鲣鱼"],
    ["crossover", "交叉"],
    ["acorn", "橡子"],
    ["bleary", "昏昏欲睡的"],
    ["lowdown", "内幕"],
    ["curation", "策展"],
    ["roulette", "轮盘赌"],
    ["limescale", "水垢"],
    ["shire", "郡"],
    ["parish", "教区"],
    ["agnostic", "uncertain, 不可知的"],
    ["chorus", "合唱"],
    ["haptic", "触觉的"],
    ["pinnacle", "巅峰"],
    ["flayed", "剥皮的"],
    ["dexterity", "adroitness, 灵巧性"],
    ["extrapolate", "推断"],
    ["cryptic", "神秘的"],
    ["amortized", "分摊的"],
    ["bibliography", "A section of a written work containing citations, not quotations, to all the books or documents referred to in the work."],
    ["lavish", "奢华的"],
    ["lair", "巢穴"],
    ["deliberative", "深思熟虑的"],
    ["guerrilla", "游击队"],
    ["carcass", "尸体"],
    ["acclimated", "适应了的"],
    ["cardinal", "基本的"],
    ["quesadilla", "墨西哥馅饼"],
    ["legend", "附有插图的简要说明"],
    ["reticent", "沉默寡言的"],
    ["efficacy", "功效"],
    ["retell", "复述"],
    ["chronicle", "编年史"],
    ["demarcated", "划定的"],
    ["bespoke", "定制的"],
    ["electromyogram", "肌电图"],
    ["electrodermal", "皮肤电刺激"],
    ["serotonin", "血清素"],
    ["noradrenaline", "去甲肾上腺素"],
    ["exert", "发挥"],
    ["amotivated", "缺乏动力的"],
    ["introjected", "incorporated unconsciously into your own psyche"],
    ["elicit", "引出"],
    ["photoplethysmography", "光电体积描记法"],
    ["galvanic", "电流的"],
    ["electroencephalography", "脑电图"],
    ["dilation", "扩张"],
    ["conscientious", "尽责的"],
    ["nominal", "名义上的"],
    ["episodic memory", "情景记忆"],
    ["vanquish", "征服"],
    ["degenerate", "退化"],
    ["monastic", "修道院的"],
    ["turkey rasher", "火鸡切片"],
    ["skirmish", "v. n. 小冲突"],
    ["actuator", "执行器"],
    ["grim", "阴沉的"],
    ["atrocious", "残暴的"],
    ["apparel", "服饰"],
    ["citrus", "柑橘"],
    ["adamant", "坚定的"],
    ["abstinence", "节制"],
    ["splinters", "碎片"],
    ["bolognese", "a sauce of ground beef, tomato, onion, and herbs"],
    ["risotto", "烩饭"],
    ["casserole", "砂锅菜"],
    ["aquifer", "含水层"],
    ["abbey", "修道院"],
    ["pastiche", "仿作"],
    ["tagliatelle", "意大利面"],
    ["cauldron", "釜"],
];
