const words = [
    ["astronomer", "天文学家"],
    ["banquet", "宴会"],
    ["oblivious", "健忘的, 无意识的"],
    ["crutch", "轮椅/拐杖"],
    ["stagnant", "停滞的"],
    ["tedious", "乏味的"],
    ["demoralizing", "令人沮丧的"],
    ["steamroll", "平推"],
    ["aperture", "光圈"],
    ["vicinity", "附近, 周围"],
    ["tweening", "补间/插值"],
    ["chasm", "裂谷, 深渊"],
    ["sentient", "有感觉的, 有意识的"],
    ["obscure", "模糊的"],
    ["damp", "潮湿的"],
    ["incentivize", "激励"],
    ["full-fledged", "成熟的, 充分发展的"],
    ["guru", "大师"],
    ["emergent", "新兴的, 紧急的"],
    ["ornate", "装饰华丽的"],
    ["magma", "岩浆"],
    ["noxious", "有害的"],
    ["gimbal lock", "万向节锁"],
    ["tandem", "串联"],
    ["extrude", "挤压"],
    ["haphazard", "偶然的, 随意的"],
    ["convex", "凸面的"],
    ["albedo", "反照率"],
    ["crevices", "裂缝"],
    ["subordinate", "下级的, 从属的"],
    ["pertain", "相关的"],
    ["hectic", "忙乱的"],
    ["agonize", "（使）极度痛苦"],
    ["puppeteer", "木偶师"],
    ["denote", "表示"],
    ["wack", "怪人"],
    ["proactive", "积极主动的"],
    ["altruistic", "利他的"],
    ["deplete", "耗尽"],
    ["refraction", "折射"],
    ["vitality", "活力, 生命力"],
    ["logistics", "物流"],
    ["syllabus", "教学大纲"],
    ["polygon", "多边形"],
    ["propagate", "传播"],
    ["notion", "概念"],
    ["presage", "预示"],
    ["spout", "喷口"],
    ["synopsis", "概要"],
    ["catapult", "弹射器"],
    ["morphing", "变形"],
    ["boffin", "专家, 科学家（俚语）"],
    ["fray", "争吵"],
    ["dodgy", "可疑的"],
    ["ample", "充足的"],
    ["allude to", "暗指"],
    ["sprite", "精灵"],
    ["atlas", "精灵图集, spritesheet"],
    ["effectively", "基本上就是..., basically"],
    ["entail", "蕴涵"],
    ["composite", "复合的"],
    ["dither", "抖动"],
    ["interleave", "交错"],
    ["palette", "调色板"],
    ["arbitrary", "人为的, 任意的"],
    ["artifacting", "伪影"],
    ["faux", "假的, 人造的"],
    ["crude", "粗糙的"],
    ["gist", "要点"],
    ["ubiquitous, omnipresent", "无处不在的"],
    ["tactile", "触觉的"],
    ["apt", "恰当的"],
    ["synonymous", "同义的"],
    ["fling", "抛"],
    ["die", "骰子"],
    ["disparate", "不同的"],
    ["fixture", "固定装置"],
    ["kinematic", "运动学的"],
    ["affix", "附加"],
    ["climatic", "气候的"],
    ["objectively", "客观地"],
    ["restitution", "恢复"],
    ["joint", "关节"],
    ["treads", "踏板"],
    ["inclined", "倾斜的"],
    ["pertinent", "相关的"],
    ["coaxial", "同轴的"],
    ["suffice to say", "可以说..."],
    ["rigid body", "刚体"],
    ["pinball", "弹球"],
    ["yield", "让..."],
    ["pitch", "俯仰"],
    ["yaw", "偏航"],
    ["polling", "轮询"],
    ["boilerplate", "模板"],
    ["caveat", "注意事项"],
    ["imposter", "冒名顶替者"],
    ["geometry", "几何体"],
    ["cue", "暗示"],
    ["spline", "样条线"],
    ["buoyancy", "浮力"],
    ["pontoon", "浮桥"],
    ["murkiness", "浑浊度"],
    ["caustics", "焦散"],
    ["ambient occlusion", "环境光遮蔽"],
    ["locomotion", "（生物体）运动"],
    ["translucent", "半透明"],
    ["decal", "贴花"],
    ["jolly", "欢乐的"],
    ["niggling", "琐碎的"],
    ["scalar", "标量"],
    ["eigenvalues", "特征值"],
    ["canonical", "标准的"],
    ["pare", "削减"],
    ["parallelogram", "平行四边形"],
    ["associativity", "关联性(结合性)"],
    ["orthonormal", "正交的"],
    ["commutative", "交换的"],
    ["applet", "小程序"],
    ["composing transforms", "组合变换"],
    ["reciprocal", "倒数"],
    ["corollary", "推论"],
    ["euler angles", "欧拉角"],
    ["quaternions", "四元数"],
    ["sanity check", "完整性检查"],
    ["trigonometry", "三角学"],
    ["jargon", "行话"],
    ["triad", "三元组"],
    ["yank", "猛拉"],
    ["designated", "指定的"],
    ["proposition", "命题"],
    ["mitigate", "减轻"],
    ["dislodge", "移位"],
    ["annealing", "退火"],
    ["applicable", "适用的"],
    ["decimal", "小数, 小数点"],
    ["interleave", "交错"],
    ["perceptron", "感知元"],
    ["outliers", "异常值"],
    ["holdout", "验证集"],
    ["suffice", "足够"],
    ["intricate", "复杂的"],
    ["plop", "放, 啪嗒声"],
    ["chronologically", "按时间顺序"],
    ["occlusions", "遮挡"],
    ["desaturate", "去饱和"],
    ["cheesy", "俗气的"],
    ["intensity", "强度"],
    ["tangent", "切线"],
    ["overhead view", "俯视图"],
    ["perspective projection", "透视投影"],
    ["focal plane", "焦平面"],
    ["frustum", "截锥体"],
    ["perturbed", "扰动的"],
    ["encompass", "包围"],
    ["discern", "辨别"],
    ["primitive", "图元"],
    ["stencil", "模板"],
    ["substitute", "替代"],
    ["uniform matrix", "均匀矩阵"],
    ["tessellation", "细分"],
    ["stride", "步长"],
    ["nuts and bolts", "螺母和螺栓"],
    ["diffuse", "散射"],
    ["specular", "镜面反射"],
    ["magenta", "品红"],
    ["advent", "到来"],
    ["glossy", "光滑的"],
    ["polished floor", "抛光之后的地板"],
    ["dielectric", "电介质"],
    ["quadratic", "二次的"],
    ["matte", "哑光的"],
    ["coarse", "粗糙的"],
    ["wood grain", "木纹"],
    ["bilinear", "双线性"],
    ["mipmap", "多级贴图"],
    ["brackets", "括号"],
    ["arbitrage", "套利"],
    ["nuance", "细微差别"],
    ["trippy", "迷幻的"],
    ["taxonomy", "分类学"],
    ["ethos", "精华"],
    ["interreflections", "互相反射"],
    ["tinge", "色调"],
    ["subsequently", "随后"],
    ["hindsight", "后见之明"],
    ["manifestation", "表现"],
    ["barycentric", "重心的"],
    ["ellipsoid", "椭球体"],
    ["nevertheless", "尽管如此"],
    ["jitter", "抖动"],
    ["jaggies", "锯齿状"],
    ["film", "画布"],
    ["cull", "剔除"],
    ["ambient", "环境的"],
    ["reminiscent", "回忆的"],
    ["finicky", "挑剔的"],
    ["nacho", "烤干酪辣味玉米片"],
    ["namely", "也就是..."],
    ["respectively", "分别"],
    ["elaborate", "阐述"],
    ["median", "中间值"],
    ["empirical", "经验的"],
    ["niche", "小众, 领域"],
    ["ecstatic", "欣喜若狂"],
    ["trivial", "琐碎的"],
    ["token", "代币, piece"],
    ["constituent", "组成的"],
    ["inaudible", "听不清的"],
    ["exhaustive", "详尽的"],
    ["fine-grained control", "细粒度控制"],
    ["inertia", "惯性"],
    ["quirks", "怪癖"],
    ["clumsy", "笨拙的"],
    ["infer", "推断"],
    ["lo and behold", "瞧！看！"],
    ["punctuation", "标点"],
    ["lingo", "行话"],
    ["pseudonymous", "匿名的"],
    ["decimal point", "小数点"],
    ["redeem", "兑换"],
    ["evident", "明显的"],
    ["schism", "分裂"],
    ["implication", "预兆"],
    ["siloed", "孤立的"],
    ["scarce", "稀缺的"],
    ["formulate", "构想"],
    ["recur", "再次发生"],
    ["convoluted", "复杂的"],
    ["admissible", "可接受的"],
    ["intractable", "难以处理的"],
    ["adversarial search", "对抗搜索"],
    ["verbose", "详细的"],
    ["deduce", "推导"],
    ["convolution", "卷积"],
    ["pooling", "汇集"],
    ["recurrent", "循环的"],
    ["modus ponens", "MP"],
    ["exclusive or", "异或"],
    ["inclusive or", "或"],
    ["entail", "蕴涵"],
    ["complimentary literals", "互补文字"],
    ["clause", "子句"],
    ["disjunction", "or"],
    ["inference by resolution", "消解推理"],
    ["quantifier", "量词"],
    ["distill", "提取"],
    ["counterfeit", "伪造(的)"],
    ["axiom", "公理"],
    ["contrived", "人为的"],
    ["heredity", "遗传"],
    ["logistic sigmoid", "逻辑S型函数"],
    ["rectified", "整流的"],
    ["circumvent", "规避"],
    ["epoch", "轮, round"],
    ["syntax", "语法"],
    ["briskly", "轻快地"],
    ["semantics", "语义"],
    ["determiner", "限定词"],
    ["prepositions", "介词"],
    ["corpus", "语料库"],
    ["wind up", "结束，..."],
    ["proportional to", "正比于..."],
    ["sentiment", "情绪"],
    ["tensor", "张量"],
    ["monetary", "货币的"],
    ["space shuttle", "航天飞机"],
    ["privilege", "特权/荣幸"],
    ["rendezvous", "会合"],
    ["low Earth orbit", "近地轨道, 200 - 2000 km"],
    ["on-orbit", "在轨的"],
    ["interplanetary", "星际的"],
    ["trajectories", "轨迹"],
    ["spaceflight", "a voyage outside the Earth's atmosphere"],
    ["principally", "主要的, chief"],
    ["robotic missions", "机器人任务"],
    ["extravehicular", "舱外的"],
    ["on two occasions", "有两次"],
    ["emphasis", "重点"],
    ["geosynchronous orbit", "地球同步轨道"],
    ["radiation belt", "辐射带"],
    ["Lagrange points", "拉格朗日点"],
    ["propulsion", "推进力"],
    ["solar arrays", "太阳能电池阵列"],
    ["servicing mission", "维修任务"],
    ["burns", "点火"],
    ["maneuvers", "动作"],
    ["space vehicle", "太空飞行器"],
    ["capsule", "舱"],
    ["flight controller", "飞行控制员"],
    ["flight director", "飞行主管（高级飞行控制员）"],
    ["elementary", "初级"],
    ["mastery", "精通, 掌握"],
    ["mechanics", "力学"],
    ["extensively", "广泛地"],
    ["astronomy", "天文学"],
    ["celestial", "天体的, 天文的"],
    ["instrumentation", "仪器"],
    ["govern...", "控制"],
    ["rotation", "自转"],
    ["refracting telescope", "折射望远镜"],
    ["lenses", "透镜"],
    ["reflecting telescope", "反射望远镜"],
    ["spacecraft", "宇宙飞船"],
    ["the law of gravitation", "万有引力定律"],
    ["propel", "推进"],
    ["interplanetary space", "行星际空间"],
    ["visionary", "有远见的"],
    ["spacefaring", "航天的"],
    ["space flight", "航天"],
    ["resounding", "高亢"],
    ["suborbital", "亚轨道, around 100 km"],
    ["boundary of space", "Kármán line, 100 km"],
    ["orbital flight", "轨道飞行"],
    ["umbilical cord", "脐带"],
    ["propulsion system", "推进系统"],
    ["subsequent", "随后的"],
    ["high paced", "快节奏"],
    ["kerosene", "煤油"],
    ["cryogenic", "低温的"],
    ["liftoff", "升空"],
    ["splashdown", "splash, down"],
    ["striking", "引人注目的"],
    ["a logical choice", "一个合理的选择"],
    ["radical", "先进的"],
    ["rugged", "崎岖"],
    ["launchpad", "发射台"],
    ["novelty", "新奇"],
    ["orbiter", "轨道飞行器"],
    ["silica tile", "硅砖"],
    ["instrument", "仪器"],
    ["antennas", "天线"],
    ["compartment", "舱室"],
    ["fuselage", "机身"],
    ["port side", "左舷"],
    ["truss", "桁架"],
    ["the outer space treaty", "外层空间条约"],
    ["orbital velocity", "轨道速度"],
    ["parties", "缔约方"],
    ["signatories", "签署方"],
    // ["Pretty much like for Antarctica, there can be no national appropriation by claim of sovereignty on any part of a celestial body."],
    ["debris", "碎片"],
    ["geostationary orbit", "地球同步轨道"],
    ["so as to", "to"],
    ["adverse changes", "不利的变化"],
    ["adopt", "采取（措施）"],
    ["graveyard", "v. put something into graveyard..."],
    ["in line with", "一致..."],
    ["stipulate", "规定, formulate"],
    ["asteroid", "小行星"],
    ["extraterrestrial", "外星的"],
    ["operate", "运营"],
    ["logistic resupply (to)...", "后勤补给"],
    ["troposphere", "对流层 6 - 20 km"],
    ["stratosphere", "平流层 50 km"],
    ["mesosphere", "中间层 85 km"],
    ["thermosphere", "热层 690 km"],
    ["exosphere", "外逸层 10,000 km"],
    ["telemetry data", "遥测数据"],
    ["constellation", "星座,（太空飞行）具有相同用途的一组卫星"],
    ["false color image", "伪彩图像"],
    ["Earth crust", "地壳"],
    ["discipline", "学科"],
    ["flux", "通量"],
    // ["Space weather is a consequence of a variation in the flux of particles in the solar wind that has an influence on the general conditions around the Earth."],
    ["physiology", "生理学"],
    ["interstellar", "星际的"],
    ["serviceable", "可维修的"],
    ["a very large catalog of...", "大量的..."],
    ["stellar system", "恒星系统"],
    ["proper motion", "自行"],
    ["radial velocity", "径向速度"],
    ["parallax", "视差"],
    ["Magellanic clouds", "麦哲伦星云"],
    ["coronagraph", "日冕仪"],
    ["constitute", "构成"],
    ["rover", "漫游者"],
    ["nucleus", "（彗星的）核心"],
    ["perihelion", "近日点"],
    ["parabola", "抛物线"],
    ["air drag", "空气阻力"],
    ["95 metric tons", "公吨"],
    ["vehicle", "载具"],
    ["super heavy-lift launch vehicles", "超重型运载火箭 > 50 t payload"],
    ["spaceports", "太空港"],
    ["oscillations", "振荡"],
    ["elasticity", "弹性"],
    ["wither away...", "远离..."],
    ["a helicoidal shape", "螺旋形状"],
    ["centrifuge", "离心机"],
    ["profile", "模式, 曲线"],
    ["longitudinal", "纵向"],
    ["trampoline", "蹦床"],
    ["vestibular", "前庭的"],
    ["exoplanet", "系外行星"],
    ["geysers", "间歇泉"],
    ["adversity", "逆境"],
    ["New Moon", "新月"],
    ["crescent", "新月"],
    ["angular", "角度的"],
    ["facultative", "可选的"],
    ["with respect to", "对于..."],
    ["subject to", "受到..."],
    ["exert", "施加"],
    ["expel", "排出"],
    ["throttle", "节流阀"],
    ["negligible", "微不足道的"],
    ["derivative", "导数"],
    ["momentum", "动量 kg·m/s"],
    ["angular momentum", "角动量"],
    ["volume", "体积"],
    ["top", "陀螺"],
    ["displacement", "位移"],
    ["analogue", "类似物"],
    ["conservation laws", "守恒定律"],
    ["potential energy", "势能"],
    ["specific energy/massic energy", "energy per unit mass, 比能, 每单位质量所具有的能量 J/kg, m^2/s^2"],
    ["kinetic energy", "动能"],
    ["electrical field", "电场"],
    ["friction", "摩擦"],
    ["velocity", "速度 m/s"],
    ["acceleration", "加速度 m/s^2"],
    ["Newton", "牛顿 kg·m/s^2"],
    ["cylinder", "圆柱"],
    ["waning moon", "残月"],
    ["elapse", "过去, 流逝, pass by"],
    ["calculus", "微积分"],
    ["secant line", "割线, the line connecting two points on a curve"],
    ["tangent line", "切线"],
    ["in a nutshell", "简而言之"],
    ["tackle", "解决（问题）"],
    ["revenue", "收入"],
    ["premier", "顶级的"],
    ["the Monaco Grand Prix", "摩纳哥大奖赛"],
    ["conglomeration", "集合体"],
    ["unravel", "解释"],
    ["skid (off, over)", "打滑"],
    ["pit crew", "维修站工作人员"],
    ["esteemed", "受人尊敬的"],
    ["inadequate", "不足"],
    ["grip", "抓地力"],
    ["hairpin turns", "发卡弯"],
    ["infamous", "臭名昭著"],
    ["dash", "破坏"],
    ["lift", "升力"],
    ["impart", "传, pass on"],
    ["driveshaft", "传动轴"],
    ["axles", "车轴"],
    ["normal force", "法向力"],
    ["normal reaction", "法向反作用力"],
    ["sheer", "陡峭的"],
    ["a visceral feeling", "一种发自内心的感觉"],
    ["beeline", "straight line"],
    ["recap", "回顾"],
    ["calamity", "灾难"],
    ["quandary", "困惑"],
    ["conundrum", "难题"],
    ["plot", "绘图"],
    ["Out-of-this-World", "超凡脱俗的"],
    ["analogy", "类比"],
    ["curvature", "曲率"],
    ["tin foil", "锡纸"],
    ["for sake of", "to"],
    ["argument", "论证"],
    ["graze", "掠过"],
    ["recipe", "方法"],
    ["difference quotient", "差商"],
    ["plummeting", "直线下降的"],
    ["hold off", "等一下"],
    ["make ... a snap", "轻而易举"],
    ["skeuomorphic", "拟物化的"],
    ["cosmopolitan", "大都会"],
    ["extensive", "广泛的"],
    ["bioreactors", "生物反应器"],
    ["nudge", "轻推"],
    ["critical point", "临界点"],
    ["maxima", "极大值"],
    ["minima", "极小值"],
    ["extremum", "极值"],
    ["punchline", "妙处"],
    ["whittle down", "削减"],
    ["second derivative test", "二阶导数检验"],
    ["saddle point", "鞍点"],
    ["placeholder", "占位符"],
    ["jerk", "加加速度"],
    ["ballpark", "球场"],
    ["Taylor series", "泰勒级数"],
    ["faucet", "龙头"],
    ["catchy", "朗朗上口的"],
    ["shore up", "支撑"],
    ["polynomials", "多项式"],
    ["power", "幂"],
    ["aside", "旁白"],
    ["difference quotient", "差商"],
    ["numerator", "分子"],
    ["sought-after", "被追捧的"],
    ["at long last", "最后, finally"],
    ["quotient", "商"],
    ["rational functions", "有理函数"],
    ["in a loose sense", "广义上"],
    ["rim", "边缘"],
    ["handy", "趁手的"],
    ["sideline", "边线"],
    ["bird's-eye view", "鸟瞰图"],
    ["near", "v. 接近"],
    ["breakaway", "突破"],
    ["fraction", "分数"],
    ["denominator", "分母"],
    ["goal", "球门"],
    ["groundwork", "基础"],
    ["so long as", "只要"],
    ["graft", "嫁接"],
    ["scoop off", "挖掉"],
    ["Riemann sum", "黎曼和"],
    ["rug", "小地毯"],
    ["Anatomy", "剖析"],
    ["definite integral", "定积分"],
    ["integral, integration", "n. integrate, 累加, 积分"],
    ["integrand", "积函数"],
    ["elongated", "拉长的"],
    ["subinterval", "子区间"],
    ["endpoint", "端点"],
    ["squared away", "解决了"],
    ["In broad strokes", "概括地说"],
    ["term", "项"],
    ["rectangle", "矩形"],
    ["versatile", "通用的"],
    // ["One of the deepest theorems in calculus says that derivatives and integrals are two sides of the same coin."],
    ["deepest", "深奥的"],
    ["theorem", "定理"],
    ["voyage", "旅程"],
    ["fission", "裂变"],
    ["fusion", "聚变"],
    ["watered-down", "淡化的"],
    ["intrepid", "勇敢的"],
    ["planar", "平面的"],
    ["net change theorem", "净变化定理"],
    ["take ... word for it", "相信...的话"],
    ["the fundamental theorem", "基本定理"],
    ["in action", "in operation"],
    ["constant of integration", "积分常数"],
    ["arithmetic", "四则运算"],
    ["bear on", "解决"],
    ["swat", "扑打"],
    ["rest", "n. 静止"],
    ["frontier", "边境"],
    ["pesky", "讨厌的"],
    ["differential equations", "微分方程"],
    ["Gabriel's horn", "加布里埃尔的号角"],
    ["paradoxical", "自相矛盾的"],
    ["surface of revolution", "旋转表面"],
    ["line segment", "线段"],
    ["differentiate, differential", "v., n. 微分"],
    ["make sense of...", "理解"],
    ["regular polygon", "正多边形"],
    ["carve up", "分割"],
    ["congruent right triangles", "全等直角三角形"],
    ["inscribe", "内切"],
    ["equilateral triangle", "等边三角形"],
    ["sequence", "序列"],
    ["cosmic rays", "宇宙射线"],
    ["radioactive", "放射性的"],
    ["replenish", "补充"],
    ["shuffled off its mortal coil", "摆脱了凡人的束缚"],
    ["proton", "质子"],
    ["exponential decay", "指数衰减"],
    ["logistic sequence", "逻辑序列"],
    ["indefinitely", "无限期地"],
    ["content ... with", "满足于"],
    ["identity", "恒等式"],
    ["infinite sum", "无限和"],
    ["The Tower of Lire", "里拉塔"],
    ["topmost", "最上面的"],
    ["overhang", "（延伸而出）悬挂"],
    ["stroke", "抚摸, caress"],
    ["awed", "敬畏的"],
    ["talent scout", "星探"],
    ["pallet", "托盘"],
    ["poised at", "在..."],
    ["pitch (to)", "提出"],
    ["meager", "微薄的"],
    ["pun", "双关语"],
    ["grand finale", "大结局"],
    ["mileage", "进展"],
    ["entry-level", "入门级的"],
    ["pizzeria", "比萨店"],
    ["infinitesimal", "无穷小"],
    ["plausible", "可信的, 似是而非的"],
    ["standard kinematics equation", "标准运动学方程"],
    ["projectile", "抛射物"],
    ["angular kinematics", "角运动学"],
    ["racetrack", "赛道"],
    ["radians", "弧度"],
    ["modulo", "mod, 模"],
    ["NASCAR", "全美改装车竞赛"],
    ["time trial", "计时赛"],
    ["crux", "关键"],
    ["oil slick", "浮油"],
    ["compositions of functions", "函数复合"],
    ["novice", "新手"],
    ["squared", "平方"],
    ["notation", "表示"],
    ["spells", "咒语"],
    ["potions", "药水"],
    ["terminology", "术语"],
    ["vertical line test", "垂直线测试"],
    ["codomain", "协域"],
    ["image", "映射"],
    ["composite function, composition", "复合函数"],
    ["inverse, inverse function", "反函数"],
    ["invertibility", "可逆性"],
    ["horizontal line test", "水平线测试"],
    ["inverse trigonometric functions", "反三角函数"],
    ["interchange", "交换"],
    ["right angle triangles", "直角三角形"],
    ["hypotenuse", "斜边"],
    ["Pythagoras theorem", "毕达哥拉斯定理"],
    ["bedrock", "基岩"],
    ["jump", "跃变"],
    ["kink", "拐点"],
    ["exponential", "指数的"],
    ["implicit functions", "隐式函数"],
    ["folium of Descartes", "笛卡儿叶形线"],
    ["cardioid", "心形线"],
    ["leverage", "利用"],
    ["singularity", "奇点"],
    ["jokingly", "开玩笑地"],
    ["rile up", "激怒"],
    ["put ... at ease", "让...放心"],
    ["rigorous", "严格的"],
    ["approximation", "近似"],
    ["Linearization", "线性化"],
    ["decimal expansion", "小数"],
    ["scheme", "方案, plan"],
    ["differential", "微小差别, 差分/微分"],
    ["gadget", "小工具"],
    ["propagation of error", "误差传播"],
    ["approximate absolute error", "近似绝对误差"],
    ["approximate relative error", "近似相对误差"],
    ["Taylor polynomial", "泰勒多项式"],
    ["discrepancy", "差异"],
    ["factorial", "阶乘, 3!"],
    ["five places of decimals", "小数点后五位"],
    ["Taylor series", "泰勒序列/泰勒级数"],
    ["Taylor's Inequality", "泰勒不等式"],
    ["rest mass", "静息质量"],
    ["special relativity", "狭义相对论"],
    ["horizontal asymptotes", "水平渐近线"],
    ["growth rates", "增长率"],
    ["equilibrium", "平衡 (plural: equilibria)"],
    ["damped oscillation", "阻尼振荡"],
    ["amplitude", "振幅"],
    ["preliminary", "初步的"],
    ["evolution", "演化"],
    ["manifests as...", "表现为..."],
    ["concentration", "浓度"],
    ["frame", "build, establish, 修建, 建立"],
    ["brass tacks", "黄铜钉"],
    ["proclaim", "宣布"],
    ["standard limits", "标准极限"],
    ["the dominant term method", "主导项方法"],
    ["Hierarchy of dominance", "主导层级"],
    ["coefficient", "系数"],
    ["squeeze theorem/sandwich theorem", "挤压定理/三明治定理"],
    ["envelope", "cage, 笼"],
    ["mutatis mutandis", "changing [only] those things which need to be changed, 稍微改改就可以"],
    ["springboard", "跳板"],
    ["sporadically", "零星地"],
    ["remark", "n. v., 注释, 评论"],
    ["signed area", "矢量面积"],
    ["disk", "圆盘"],
    ["elaborate", "adj. very detailed and complicated"],
    ["refrain from", "避免"],
    ["kick things up a notch", "让事情更上一层楼"],
    ["anti-derivative", "反导数"],
    ["Fresnel function", "菲涅尔函数"],
    ["peculiar", "奇特的"],
    ["ins and outs", "来龙去脉"],
    ["subtlety", "微妙"],
    ["facilitate", "promote, 促进"],
    ["bread and butter", "基石"],
    ["in a way", "from some points of view"],
    ["culmination", "高潮, climax"],
    ["endeavor", "work hard/hard work"],
    ["gauge", "初始值"],
    ["initial value problems", "初始值问题"],
    ["solvent", "溶剂"],
    ["solution", "溶液"],
    ["direction fields", "方向场"],
    ["autonomous equation", "自治方程"],
    ["separable differential equations", "可分离微分方程"],
    ["factorize", "因式分解"],
    ["linear differential equations", "线性微分方程"],
    ["integrating factor", "积分因子"],
    ["ansatz", "guessing"],
    ["indispensable", "不可或缺的"],
    ["subscripts", "下标"],
    ["superscripts", "上标"],
    ["summation", "累加"],
    ["read off (information)", "读取"],
    ["qualitative", "定性的"],
    ["level headed", "头脑冷静的, cool-headed"],
    ["maximal domain", "最大域"],
    ["practical domain", "实用的域"],
    ["Cartesian coordinate system", "笛卡尔坐标系"],
    ["level curve", "等高线"],
    ["contour", "轮廓"],
    ["level surface", "等值面"],
    ["paraboloid", "抛物面"],
    ["partial derivatives", "分导数"],
    ["d", "dee, total derivative"],
    ["∂", "del, partial derivative"],
    ["passage", "通道"],
    ["Clairaut's theorem", "克莱罗定理"],
    ["evaluate", "评估"],
    ["begs... (the question)", "引出了"],
    ["quest", "探索 - exploration, 追寻 - pursue"],
    ["oversight", "疏忽, negligence"],
    ["Directional derivatives", "方向导数"],
    ["sinusoidal", "正弦曲线的"],
    ["cross-section", "横截面"],
    ["normal form", "法线形式, ax + by = c"],
    ["preempt", "抢先"],
    ["transversal", "横向的"],
    ["cusp", "spike, 尖点"],
    ["inconclusive", "不确定的"],
    ["Hessian matrix", "黑塞矩阵"],
    ["eigenvalues", "特征值"],
    ["streamlined", "精简的"],
    ["legend", "图例"],
    ["interior", "adj. n., 内部（的）"],
    ["criterium", "criterion, 标准, criteria (plural)"],
    ["in a row", "adv. 连续"],
    ["lamina", "薄片"],
    ["a loaf of bread", "一条面包"],
    ["oblique line", "斜线"],
    ["hyperbola", "双曲线"],
    ["isosceles", "等腰的"],
    ["circular symmetries", "圆对称性"],
    ["arc length", "弧长"],
    ["Jacobian", "雅可比因子"],
    ["iterated integral", "迭代积分"],
    ["tetrahedron", "四面体"],
    ["rotational symmetries", "旋转对称性"],
    ["hemisphere", "半球"],
    ["latitude-longitude coordinates system", "经纬度坐标系"],
    ["mine shaft", "矿井"],
    ["spherical symmetries", "球对称性"],
    ["spinning top", "陀螺"],
    ["scone", "司康饼"],
    ["treatise", "论述, study"],
    ["scientific notation", "科学计数法"],
    ["round ...", "四舍五入"],
    ["significant digits/figures", "有效数字"],
    ["adequate", "足够的"],
    ["take about ...", "考虑一下..., consider"],
    ["well-versed", "精通的"],
    ["algebra", "运算结构学, 代数"],
    ["kinematics", "运动学"],
    ["motion", "运动"],
    ["slate board", "板岩板"],
    ["in motion", "在运动的"],
    ["plainspoken", "直言不讳的"],
    ["electrons", "电子"],
    ["protons", "质子"],
    ["neutrons", "中子"],
    ["soak in...", "savor, 沉浸, 品味"],
    ["throw in the towel", "认输"],
    ["Joules", "焦耳 N·m, kg·m^2/s^2"],
    ["teeny bit", "一点点"],
    ["Work", "功, W = F(vec) · Δr(vec), kg·m^2/s^2"],
    ["street definition", "街头定义"],
    ["Power", "\"how fast you are working\", P = F(vec) · v(vec),"],
    ["ramp", "坡道"],
    ["Mechanical Energy", "力能, 机械能"],
    ["Conservative Forces", "\"they dont waste energy\" - gravitational, spring forces, electrostatic"],
    ["gravitation", "引力"],
    ["gravity", "重力"],
    ["Momentum", "P(vec) = mv(vec), 动量"],
    ["repulsive", "<->"],
    ["sterile", "无菌的"],
    ["Large Hadron Collider (LHC)", "大型强子对撞机"],
    ["Higgs", "希格斯粒子"],
    ["splat", "split"],
    ["contemplative", "沉思的"],
    ["exhaust", "排气"],
    ["pendulum", "钟摆"],
    ["conserved", "守恒的"],
    ["repulsive force", "斥力"],
    ["artistry", "艺术"],
    ["barge", "驳船"],
    ["amphitheater", "露天剧场"],
    ["expend", "花费"],
    ["nirvana", "涅槃"],
    ["indulge", "放纵"],
    ["dojo", "道场"],
    ["uniform circular motion", "匀速圆周运动"],
    ["characterize", "formalize"],
    ["centripetal (center seeking) acceleration", "向心加速度"],
    ["circumference", "圆周, 周长"],
    ["tangential", "切向的"],
    ["radial", "径向的"],
    ["radii", "半径"],
    ["extended object", "拉伸对象"],
    ["tricky", "棘手的"],
    ["spokes", "辐条"],
    ["Rotational Kinetic Energy", "旋转动能"],
    ["moment/moment of inertia", "惯性力矩"],
    ["unwind", "展开"],
    ["prism", "棱柱"],
    ["azimuthal angle", "方位角"],
    ["Torque", "扭矩, a force around an axis"],
    ["hinge", "pivot, 枢"],
    ["gravitas", "庄重"],
    ["Atwood Machine", "阿特伍德机器"],
    ["redux", "adj. n., a theme or topic redone, restored, brought back, or revisited"],
    ["pulley", "滑轮"],
    ["envision", "构想"],
    ["strip lights", "灯带"],
    ["cycloid", "摆线"],
    ["Mm, foreshadowing.", "嗯，有预感。"],
    ["pun", "双关语"],
    ["timeless", "永恒的"],
    ["revolution", "旋转（一周）"],
    ["precess(ion)", "Falling with style. 绕轴旋转"],
    ["fidget", "坐立不安"],
    ["cubicle", "小隔间"],
    ["gyroscope", "陀螺仪"],
    ["gimbal mount", "万向架"],
    ["provincial", "狭隘的"],
    ["apparatus", "仪器"],
    ["moose", "驼鹿"],
    ["elliptical orbits", "椭圆轨道"],
    ["semi-major axis", "半长轴, long radius"],
    ["semi-minor axis", "半短轴, short radius"],
    ["eccentricity", "偏心率"],
    ["Halley's Comet", "哈雷彗星"],
    ["Gravitational Field", "引力场"],
    ["gravity well", "重力井"],
    ["Escape Velocity", "逃逸速度"],
    ["event horizon", "事件视界"],
];
